plugins:
  - name: test-app
    id: test-app
    uses:
      - plugin: http://localhost:5000
        runsOn: ["issue_comment.created"]
        with: 
          model: "nousresearch/hermes-3-llama-3.1-405b"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
          
