plugins:
  - name: test-app
    id: test-app
    uses:
      - plugin: http://localhost:5000
        runsOn: ["issue_comment.created"]
        with: 
          model: "microsoft/phi-3.5-mini-128k-instruct"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
