plugins:
  - name: test-app
    id: test-app
    uses:
      - plugin: http://localhost:5000
        runsOn: [ "issue_comment.created", "issue_comment.edited", "issue_comment.deleted", "issues.opened", "issues.edited", "issues.deleted", "issues.labled" ]
        with: 
          matchThreshold: 0.95
          warningThreshold: 0.75
          jobMatchingThreshold: 0.75

