plugins:
  - name: test-app
    id: test-app
    uses:
      - plugin: http://localhost:5000
        runsOn: ["issue_comment.created"]
        with: 
          model: "google/gemini-flash-1.5-8b"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
