name: Manually Generate PR using Aider

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue Number"
        required: true
        type: string
      base-branch:
        description: "Base Branch"
        required: true
        type: string

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  generate:
    uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main
    with:
      issue-number: ${{ inputs.issue-number }}  # Remove quotes
      base-branch: ${{ inputs.base-branch }}  # Remove quotes
      model: "anthropic/claude-3.5-sonnet"
    secrets:
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
