name: Manually Generate PR using Aider

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue Number"
        required: true
        type: string  # Ensure it's a string
      base-branch:
        description: "Base Branch"
        required: true
        type: string  # Ensure it's a string

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  generate:
    uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main
    with:
      issue-number: "${{ inputs.issue-number }}"  # Explicitly ensure it's treated as a string
      base-branch: "${{ inputs.base-branch }}"  # Explicitly ensure it's treated as a string
      model: "anthropic/claude-3.5-sonnet"
    secrets:
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
