name: SWE-agent-hybrid
on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Bun for repository
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install repository dependencies
        run: |
          bun install
        shell: bash

      - name: Clone SWE-agent
        run: |
          git clone https://github.com/SWE-agent/SWE-agent.git
        shell: bash

      - name: Install Python Dependencies
        run: |
          cd SWE-agent
          python -m pip install --upgrade pip
          pip install --editable .
        shell: bash

      - name: Run setup script and create keys.cfg
        run: |
          cd SWE-agent
          chmod +x setup.sh
          ./setup.sh
          echo "GITHUB_TOKEN: '${{ secrets.GITHUB_ACCESS_TOKEN }}'" > keys.cfg
          echo "OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'" >> keys.cfg
          echo "ANTHROPIC_API_KEY: '${{ secrets.ANTHROPIC_API_KEY }}'" >> keys.cfg
          echo "TOGETHER_API_KEY: ''" >> keys.cfg
        shell: bash

      - name: Run script with environment variables
        env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          cd SWE-agent
          python run.py --model_name gpt4 \
            --data_path $ISSUE_URL \
            --config_file config/default_from_url.yaml \
            --open_pr true \
            --per_instance_cost_limit 3.0
        shell: bash


      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # # Process repository changes with Bun
      # - name: Run repository build/tests
      #   run: |
      #     bun run build
      #     bun run test
      #   shell: bash

      - name: Create PR branch
        run: |
          BRANCH_NAME="fix/issue-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "fix: Implement solution for issue #${{ github.event.issue.number }}"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          commit-message: "fix: Implement solution for issue #${{ github.event.issue.number }}"
          title: "fix: Solution for issue #${{ github.event.issue.number }}"
          body: |
            This PR implements a solution for issue #${{ github.event.issue.number }}
            
            Automated changes by SWE-agent
            
            - Solution generated using Claude 3 Opus via OpenRouter
            - Build and tests passed using Bun
          branch: fix/issue-${{ github.event.issue.number }}
          base: main
          draft: false
